import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageController {
  LanguageController._();

  static const String _storageKey = 'nbts_language_code';
  static final ValueNotifier<String> code = ValueNotifier<String>('en');

  static Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString(_storageKey);
    if (saved == 'sw' || saved == 'en') code.value = saved!;
  }

  static Future<void> set(String value) async {
    final normalized = value == 'sw' || value.toLowerCase() == 'swahili'
        ? 'sw'
        : 'en';
    if (code.value == normalized) return;
    code.value = normalized;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_storageKey, normalized);
  }

  static String label(String value) {
    final normalized = value.toLowerCase().trim();
    if (normalized == 'sw' ||
        normalized == 'swahili' ||
        normalized == 'kiswahili') {
      return 'Swahili';
    }
    return 'English';
  }
}

extension AppText on BuildContext {
  String t(String key) => AppStrings.text(key, LanguageController.code.value);
}

class AppStrings {
  AppStrings._();

  static String text(String key, String code) {
    final map = code == 'sw' ? _sw : _en;
    return map[key] ?? _en[key] ?? key;
  }

  static const Map<String, String> _en = {
    'app.name': 'NBTS',
    'welcome.title1': 'Donate blood.',
    'welcome.title2': 'Save lives.',
    'welcome.subtitle':
        'Book donation appointments, track your donor profile, and carry your secure NBTS donor card.',
    'welcome.feature.profile': 'Create and manage your donor profile',
    'welcome.feature.appointments': 'Book and view donation appointments',
    'welcome.feature.card': 'Carry your secure digital donor card',
    'auth.signIn': 'Sign in',
    'auth.createAccount': 'Create an account',
    'auth.loginSubtitle': 'Use the email or phone you registered with.',
    'auth.emailPhone': 'Email or phone',
    'auth.emailPhoneHint': 'Email or phone number',
    'auth.password': 'Password',
    'auth.newAccount': 'New to NBTS?  Create an account',
    'auth.privacyAccept': 'By continuing you accept the Privacy Policy.',
    'auth.registerTitle': 'Donor registration',
    'auth.registerSubtitle':
        'Tell us a bit about you to set up your NBTS donor profile.',
    'auth.account': 'Account',
    'auth.fullName': 'Full name',
    'auth.emailOptional': 'Email (optional)',
    'auth.phone': 'Phone',
    'auth.donorProfile': 'Donor profile',
    'auth.bloodGroup': 'Blood group',
    'auth.gender': 'Gender',
    'auth.region': 'Region',
    'auth.dateOfBirth': 'Date of birth',
    'auth.selectDate': 'Select date',
    'auth.terms': 'I accept the Terms, Privacy Policy and health-data notice.',
    'auth.haveAccount': 'Already have an account?  Sign in',
    'auth.required': 'Required',
    'auth.validEmail': 'Enter a valid email',
    'auth.validPhone': 'Enter a valid phone',
    'auth.passwordLength': 'Use at least 8 characters',
    'nav.home': 'Home',
    'nav.book': 'Book',
    'nav.centers': 'Centers',
    'nav.history': 'History',
    'nav.profile': 'Profile',
    'common.pending': 'Pending',
    'common.pendingMedical': 'Pending medical verification',
    'common.seeAll': 'See all',
    'common.refresh': 'Refresh',
    'dashboard.welcome': 'Welcome',
    'dashboard.welcomeDonor': 'Welcome donor',
    'dashboard.quickActions': 'Quick actions',
    'dashboard.forYou': 'For you',
    'dashboard.eligibility': 'Eligibility',
    'dashboard.eligible': 'Eligible',
    'dashboard.eligibleDonate': 'Eligible to donate',
    'dashboard.nextEligible': 'Next eligible',
    'dashboard.bookDonation': 'Book donation',
    'dashboard.donorCard': 'Donor card',
    'dashboard.donations': 'Donations',
    'dashboard.volume': 'Volume',
    'dashboard.findCenter': 'Find center',
    'dashboard.card': 'Card',
    'profile.title': 'Profile',
    'profile.account': 'Account',
    'profile.donorCard': 'Donor card',
    'profile.medicalSummary': 'Medical summary',
    'profile.emergencyContact': 'Emergency contact',
    'profile.notifications': 'Notifications',
    'profile.pushNotifications': 'Push notifications',
    'profile.smsReminders': 'SMS reminders',
    'profile.appearance': 'Appearance',
    'profile.light': 'Light',
    'profile.dark': 'Dark',
    'profile.system': 'System',
    'profile.language': 'Language',
    'profile.support': 'Support',
    'profile.faq': 'FAQ and donor guide',
    'profile.contactSupport': 'Contact NBTS support',
    'profile.privacy': 'Account and privacy',
    'profile.signOut': 'Sign out',
    'profile.nbtsId': 'NBTS ID',
    'profile.blood': 'Blood',
    'profile.donorPoints': 'Donor points',
    'profile.photoUpdated': 'Profile photo updated.',
    'medical.openCard': 'Open donor card',
    'medical.totalDonations': 'Total donations',
    'donorCard.title': 'Donor card',
    'donorCard.digital': 'NBTS DIGITAL CARD',
    'donorCard.bloodVerified': 'Blood group verified',
    'donorCard.qrTitle': 'Express check-in',
    'donorCard.qrSubtitle': 'Show this code at any NBTS center.',
    'donorCard.homeCenter': 'Home center',
    'donorCard.qrExpires': 'QR expires',
    'donorCard.copied': 'Donor card details copied.',
    'complete.editProfile': 'Edit profile',
    'complete.completeProfile': 'Complete profile',
    'complete.editTitle': 'Edit your donor profile',
    'complete.finishTitle': 'Finish your donor profile',
    'complete.editSubtitle':
        'Update the donor details NBTS uses for eligibility, appointments, and your donor card.',
    'complete.finishSubtitle':
        'Google or Apple confirms your identity. NBTS still needs donor details before appointments and donor card access.',
    'complete.required': 'Required',
    'complete.optional': 'Optional',
    'complete.preferences': 'Preferences',
    'complete.address': 'Address',
    'complete.preferredCenter': 'Preferred blood center',
    'complete.emergencyName': 'Emergency contact name',
    'complete.emergencyPhone': 'Emergency contact phone',
    'complete.saveChanges': 'Save changes',
    'complete.saveContinue': 'Save and continue',
    'complete.useAnother': 'Use another account',
    'complete.loadingCenters': 'Loading centers',
    'complete.noCenters': 'No centers available',
    'complete.selectCenter': 'Select center',
    'book.title': 'Book donation',
    'book.rescheduleTitle': 'Reschedule donation',
    'book.center': 'Center',
    'book.date': 'Date',
    'book.time': 'Time',
    'book.donationCenter': 'Donation center',
    'book.chooseCenter': 'Choose center',
    'book.tip': 'Have a meal and water 2 hours before donating.',
    'book.selectTime': 'Select a time',
    'book.confirm': 'Confirm appointment',
    'book.save': 'Save appointment',
    'book.retry': 'Retry',
    'centers.title': 'Centers',
    'centers.subtitle':
        'Find NBTS locations, opening details, services, and booking availability.',
    'centers.search': 'Search by name or area',
    'centers.unavailable': 'Centers unavailable',
    'centers.none': 'No centers found',
    'centers.noneMessage': 'Try another area or pull to refresh NBTS centers.',
    'centers.addressPending': 'Address pending',
    'centers.hoursPending': 'Hours pending',
    'centers.phonePending': 'Phone pending',
    'centers.open': 'Open',
    'centers.closed': 'Closed',
    'centers.bookHere': 'Book here',
    'history.title': 'History',
    'history.subtitle':
        'Track your donation impact, verified visits, and next action.',
    'history.impact': 'Impact',
    'history.totalDonated': 'Total donated',
    'history.noRecords': 'No records yet',
    'history.noRecordsMessage':
        'Verified donation records will appear once NBTS syncs your data.',
    'history.scheduleNext': 'Schedule next donation',
    'history.records': 'Donation records',
    'history.recordsInfo':
        'This view shows all donation records currently synced from NBTS. Filters will become available when more record categories are provided by the backend.',
    'common.done': 'Done',
    'notifications.title': 'Notifications',
    'notifications.markRead': 'Mark read',
    'notifications.unavailable': 'Notifications unavailable',
    'notifications.empty': 'No notifications yet',
    'notifications.emptyMessage':
        'NBTS alerts, appointments, and campaign updates will appear here.',
    'appointments.title': 'Appointments',
    'appointments.unavailable': 'Appointments unavailable',
    'appointments.next': 'Next appointment',
    'appointments.all': 'All appointments',
    'appointments.noneBooked': 'No appointment booked',
    'appointments.noneBookedMessage': 'Book a donation to see your upcoming visit details here.',
    'appointments.bookNew': 'Book new donation',
    'appointments.change': 'Change appointment',
    'appointments.noneYet': 'No appointments yet',
    'appointments.noneYetMessage': 'Your upcoming and past bookings will appear here.',
    'appointments.cancelTitle': 'Cancel appointment?',
    'appointments.cancelMessage': 'This appointment will be marked as cancelled.',
    'appointments.keep': 'Keep',
    'appointments.cancelAppointment': 'Cancel appointment',
    'appointments.cancelled': 'Appointment cancelled.',
    'appointments.status': 'Status',
    'appointments.reschedule': 'Reschedule',
    'appointments.cancel': 'Cancel',
    'appointments.datePending': 'Date pending',
    'appointments.centerPending': 'NBTS center',
    'status.pendingConfirmation': 'Pending',
    'status.confirmed': 'Confirmed',
    'status.rescheduled': 'Rescheduled',
    'status.cancelled': 'Cancelled',
    'status.completed': 'Completed',
    'status.missed': 'Missed',
    'status.upcoming': 'Upcoming',
  };

  static const Map<String, String> _sw = {
    'app.name': 'NBTS',
    'welcome.title1': 'Changia damu.',
    'welcome.title2': 'Okoa maisha.',
    'welcome.subtitle':
        'Weka miadi ya kuchangia damu, fuatilia wasifu wako, na tumia kadi yako salama ya NBTS.',
    'welcome.feature.profile': 'Tengeneza na simamia wasifu wako wa mchangiaji',
    'welcome.feature.appointments': 'Weka na tazama miadi ya kuchangia',
    'welcome.feature.card': 'Beba kadi yako salama ya kidijitali',
    'auth.signIn': 'Ingia',
    'auth.createAccount': 'Fungua akaunti',
    'auth.loginSubtitle': 'Tumia barua pepe au simu uliyojisajili nayo.',
    'auth.emailPhone': 'Barua pepe au simu',
    'auth.emailPhoneHint': 'Barua pepe au namba ya simu',
    'auth.password': 'Nenosiri',
    'auth.newAccount': 'Mgeni NBTS?  Fungua akaunti',
    'auth.privacyAccept': 'Kwa kuendelea unakubali Sera ya Faragha.',
    'auth.registerTitle': 'Usajili wa mchangiaji',
    'auth.registerSubtitle':
        'Tupe taarifa zako ili kuanzisha wasifu wako wa NBTS.',
    'auth.account': 'Akaunti',
    'auth.fullName': 'Jina kamili',
    'auth.emailOptional': 'Barua pepe (si lazima)',
    'auth.phone': 'Simu',
    'auth.donorProfile': 'Wasifu wa mchangiaji',
    'auth.bloodGroup': 'Kundi la damu',
    'auth.gender': 'Jinsia',
    'auth.region': 'Mkoa',
    'auth.dateOfBirth': 'Tarehe ya kuzaliwa',
    'auth.selectDate': 'Chagua tarehe',
    'auth.terms': 'Ninakubali Masharti, Sera ya Faragha na taarifa ya afya.',
    'auth.haveAccount': 'Una akaunti tayari?  Ingia',
    'auth.required': 'Inahitajika',
    'auth.validEmail': 'Weka barua pepe sahihi',
    'auth.validPhone': 'Weka simu sahihi',
    'auth.passwordLength': 'Tumia angalau herufi 8',
    'nav.home': 'Nyumbani',
    'nav.book': 'Weka miadi',
    'nav.centers': 'Vituo',
    'nav.history': 'Historia',
    'nav.profile': 'Wasifu',
    'common.pending': 'Inasubiri',
    'common.pendingMedical': 'Inasubiri uthibitisho wa kitabibu',
    'common.seeAll': 'Tazama yote',
    'common.refresh': 'Onyesha upya',
    'dashboard.welcome': 'Karibu',
    'dashboard.welcomeDonor': 'Karibu mchangiaji',
    'dashboard.quickActions': 'Vitendo vya haraka',
    'dashboard.forYou': 'Kwa ajili yako',
    'dashboard.eligibility': 'Ustahiki',
    'dashboard.eligible': 'Unastahiki',
    'dashboard.eligibleDonate': 'Unastahiki kuchangia',
    'dashboard.nextEligible': 'Ustahiki unaofuata',
    'dashboard.bookDonation': 'Weka miadi',
    'dashboard.donorCard': 'Kadi ya mchangiaji',
    'dashboard.donations': 'Michango',
    'dashboard.volume': 'Kiasi',
    'dashboard.findCenter': 'Tafuta kituo',
    'dashboard.card': 'Kadi',
    'profile.title': 'Wasifu',
    'profile.account': 'Akaunti',
    'profile.donorCard': 'Kadi ya mchangiaji',
    'profile.medicalSummary': 'Muhtasari wa afya',
    'profile.emergencyContact': 'Mawasiliano ya dharura',
    'profile.notifications': 'Arifa',
    'profile.pushNotifications': 'Arifa za programu',
    'profile.smsReminders': 'Vikumbusho vya SMS',
    'profile.appearance': 'Mwonekano',
    'profile.light': 'Mwanga',
    'profile.dark': 'Giza',
    'profile.system': 'Mfumo',
    'profile.language': 'Lugha',
    'profile.support': 'Msaada',
    'profile.faq': 'Maswali na mwongozo',
    'profile.contactSupport': 'Wasiliana na NBTS',
    'profile.privacy': 'Akaunti na faragha',
    'profile.signOut': 'Toka',
    'profile.nbtsId': 'NBTS ID',
    'profile.blood': 'Damu',
    'profile.donorPoints': 'Pointi za mchangiaji',
    'profile.photoUpdated': 'Picha ya wasifu imesasishwa.',
    'medical.openCard': 'Fungua kadi ya mchangiaji',
    'medical.totalDonations': 'Jumla ya michango',
    'donorCard.title': 'Kadi ya mchangiaji',
    'donorCard.digital': 'KADI YA KIDIJITALI NBTS',
    'donorCard.bloodVerified': 'Kundi la damu limethibitishwa',
    'donorCard.qrTitle': 'Kuingia haraka',
    'donorCard.qrSubtitle':
        'Onyesha msimbo huu kwenye kituo chochote cha NBTS.',
    'donorCard.homeCenter': 'Kituo chako',
    'donorCard.qrExpires': 'QR inaisha',
    'donorCard.copied': 'Taarifa za kadi zimenakiliwa.',
    'complete.editProfile': 'Hariri wasifu',
    'complete.completeProfile': 'Kamilisha wasifu',
    'complete.editTitle': 'Hariri wasifu wako wa mchangiaji',
    'complete.finishTitle': 'Kamilisha wasifu wako wa mchangiaji',
    'complete.editSubtitle':
        'Sasisha taarifa NBTS inazotumia kwa ustahiki, miadi, na kadi yako.',
    'complete.finishSubtitle':
        'Google au Apple huthibitisha utambulisho wako. NBTS bado inahitaji taarifa za mchangiaji.',
    'complete.required': 'Inahitajika',
    'complete.optional': 'Si lazima',
    'complete.preferences': 'Mapendeleo',
    'complete.address': 'Anwani',
    'complete.preferredCenter': 'Kituo unachopendelea',
    'complete.emergencyName': 'Jina la mawasiliano ya dharura',
    'complete.emergencyPhone': 'Simu ya dharura',
    'complete.saveChanges': 'Hifadhi mabadiliko',
    'complete.saveContinue': 'Hifadhi na endelea',
    'complete.useAnother': 'Tumia akaunti nyingine',
    'complete.loadingCenters': 'Inapakia vituo',
    'complete.noCenters': 'Hakuna vituo',
    'complete.selectCenter': 'Chagua kituo',
    'book.title': 'Weka miadi',
    'book.rescheduleTitle': 'Badilisha miadi',
    'book.center': 'Kituo',
    'book.date': 'Tarehe',
    'book.time': 'Muda',
    'book.donationCenter': 'Kituo cha kuchangia',
    'book.chooseCenter': 'Chagua kituo',
    'book.tip': 'Kula chakula na kunywa maji saa 2 kabla ya kuchangia.',
    'book.selectTime': 'Chagua muda',
    'book.confirm': 'Thibitisha miadi',
    'book.save': 'Hifadhi miadi',
    'book.retry': 'Jaribu tena',
    'centers.title': 'Vituo',
    'centers.subtitle':
        'Tafuta vituo vya NBTS, saa za kazi, huduma, na nafasi za kuweka miadi.',
    'centers.search': 'Tafuta kwa jina au eneo',
    'centers.unavailable': 'Vituo havipatikani',
    'centers.none': 'Hakuna vituo vilivyopatikana',
    'centers.noneMessage':
        'Jaribu eneo jingine au vuta kusasisha vituo vya NBTS.',
    'centers.addressPending': 'Anwani inasubiri',
    'centers.hoursPending': 'Saa zinasubiri',
    'centers.phonePending': 'Simu inasubiri',
    'centers.open': 'Wazi',
    'centers.closed': 'Imefungwa',
    'centers.bookHere': 'Weka miadi hapa',
    'history.title': 'Historia',
    'history.subtitle':
        'Fuatilia mchango wako, ziara zilizothibitishwa, na hatua inayofuata.',
    'history.impact': 'Mchango wako',
    'history.totalDonated': 'Jumla iliyochangiwa',
    'history.noRecords': 'Hakuna rekodi bado',
    'history.noRecordsMessage':
        'Rekodi zilizothibitishwa zitaonekana NBTS ikisawazisha taarifa zako.',
    'history.scheduleNext': 'Panga mchango unaofuata',
    'history.records': 'Rekodi za uchangiaji',
    'history.recordsInfo':
        'Hapa unaona rekodi zote zilizosawazishwa kutoka NBTS. Vichujio vitaongezwa backend ikitoa makundi zaidi.',
    'common.done': 'Sawa',
    'notifications.title': 'Arifa',
    'notifications.markRead': 'Weka zimesomwa',
    'notifications.unavailable': 'Arifa hazipatikani',
    'notifications.empty': 'Hakuna arifa bado',
    'notifications.emptyMessage':
        'Arifa za NBTS, miadi, na kampeni zitaonekana hapa.',
    'appointments.title': 'Miadi',
    'appointments.unavailable': 'Miadi haipatikani',
    'appointments.next': 'Miadi ijayo',
    'appointments.all': 'Miadi yote',
    'appointments.noneBooked': 'Hakuna miadi iliyowekwa',
    'appointments.noneBookedMessage': 'Weka miadi ya kuchangia ili uone taarifa za ziara yako hapa.',
    'appointments.bookNew': 'Weka miadi mpya',
    'appointments.change': 'Badilisha miadi',
    'appointments.noneYet': 'Hakuna miadi bado',
    'appointments.noneYetMessage': 'Miadi yako ya sasa na ya zamani itaonekana hapa.',
    'appointments.cancelTitle': 'Ghairi miadi?',
    'appointments.cancelMessage': 'Miadi hii itawekwa kama imeghairiwa.',
    'appointments.keep': 'Baki nayo',
    'appointments.cancelAppointment': 'Ghairi miadi',
    'appointments.cancelled': 'Miadi imeghairiwa.',
    'appointments.status': 'Hali',
    'appointments.reschedule': 'Badilisha',
    'appointments.cancel': 'Ghairi',
    'appointments.datePending': 'Tarehe inasubiri',
    'appointments.centerPending': 'Kituo cha NBTS',
    'status.pendingConfirmation': 'Inasubiri',
    'status.confirmed': 'Imethibitishwa',
    'status.rescheduled': 'Imebadilishwa',
    'status.cancelled': 'Imeghairiwa',
    'status.completed': 'Imekamilika',
    'status.missed': 'Imepitwa',
    'status.upcoming': 'Ijayo',
  };
}

