import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageController {
  LanguageController._();

  static const String _storageKey = 'nbts_language_code';
  static final ValueNotifier<String> code = ValueNotifier<String>('en');

  static Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString(_storageKey);
    if (saved == 'sw' || saved == 'en') code.value = saved!;
  }

  static Future<void> set(String value) async {
    final normalized = value == 'sw' || value.toLowerCase() == 'swahili'
        ? 'sw'
        : 'en';
    if (code.value == normalized) return;
    code.value = normalized;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_storageKey, normalized);
  }

  static String label(String value) {
    final normalized = value.toLowerCase().trim();
    if (normalized == 'sw' ||
        normalized == 'swahili' ||
        normalized == 'kiswahili') {
      return 'Swahili';
    }
    return 'English';
  }
}

extension AppText on BuildContext {
  String t(String key) => AppStrings.text(key, LanguageController.code.value);
}

class AppStrings {
  AppStrings._();

  static String text(String key, String code) {
    final map = code == 'sw' ? _sw : _en;
    return map[key] ?? _en[key] ?? key;
  }

  static const Map<String, String> _en = {
    'app.name': 'NBTS',
    'welcome.title1': 'Donate blood.',
    'welcome.title2': 'Save lives.',
    'welcome.subtitle':
        'Book donation appointments, track your donor profile, and carry your secure NBTS donor card.',
    'welcome.feature.profile': 'Create and manage your donor profile',
    'welcome.feature.appointments': 'Book and view donation appointments',
    'welcome.feature.card': 'Carry your secure digital donor card',
    'auth.signIn': 'Sign in',
    'auth.createAccount': 'Create an account',
    'auth.loginSubtitle': 'Use the email or phone you registered with.',
    'auth.emailPhone': 'Email or phone',
    'auth.emailPhoneHint': 'Email or phone number',
    'auth.password': 'Password',
    'auth.newAccount': 'New to NBTS?  Create an account',
    'auth.privacyAccept': 'By continuing you accept the Privacy Policy.',
    'auth.registerTitle': 'Donor registration',
    'auth.registerSubtitle':
        'Tell us a bit about you to set up your NBTS donor profile.',
    'auth.account': 'Account',
    'auth.fullName': 'Full name',
    'auth.emailOptional': 'Email (optional)',
    'auth.phone': 'Phone',
    'auth.donorProfile': 'Donor profile',
    'auth.bloodGroup': 'Blood group',
    'auth.gender': 'Gender',
    'auth.region': 'Region',
    'auth.dateOfBirth': 'Date of birth',
    'auth.selectDate': 'Select date',
    'auth.terms': 'I accept the Terms, Privacy Policy and health-data notice.',
    'auth.haveAccount': 'Already have an account?  Sign in',
    'auth.required': 'Required',
    'auth.validEmail': 'Enter a valid email',
    'auth.validPhone': 'Enter a valid phone',
    'auth.passwordLength': 'Use at least 8 characters',
    'nav.home': 'Home',
    'nav.book': 'Book',
    'nav.centers': 'Centers',
    'nav.history': 'History',
    'nav.profile': 'Profile',
    'common.pending': 'Pending',
    'common.pendingMedical': 'Pending medical verification',
    'common.seeAll': 'See all',
    'common.refresh': 'Refresh',
    'dashboard.welcome': 'Welcome',
    'dashboard.welcomeDonor': 'Welcome donor',
    'dashboard.quickActions': 'Quick actions',
    'dashboard.forYou': 'For you',
    'dashboard.eligibility': 'Eligibility',
    'dashboard.eligible': 'Eligible',
    'dashboard.eligibleDonate': 'Eligible to donate',
    'dashboard.nextEligible': 'Next eligible',
    'dashboard.bookDonation': 'Book donation',
    'dashboard.donorCard': 'Donor card',
    'dashboard.donations': 'Donations',
    'dashboard.volume': 'Volume',
    'dashboard.findCenter': 'Find center',
    'dashboard.card': 'Card',
    'profile.title': 'Profile',
    'profile.account': 'Account',
    'profile.donorCard': 'Donor card',
    'profile.medicalSummary': 'Medical summary',
    'profile.emergencyContact': 'Emergency contact',
    'profile.notifications': 'Notifications',
    'profile.pushNotifications': 'Push notifications',
    'profile.smsReminders': 'SMS reminders',
    'profile.appearance': 'Appearance',
    'profile.light': 'Light',
    'profile.dark': 'Dark',
    'profile.system': 'System',
    'profile.language': 'Language',
    'profile.support': 'Support',
    'profile.faq': 'FAQ and donor guide',
    'profile.contactSupport': 'Contact NBTS support',
    'profile.privacy': 'Account and privacy',
    'profile.signOut': 'Sign out',
    'profile.nbtsId': 'NBTS ID',
    'profile.blood': 'Blood',
    'profile.donorPoints': 'Donor points',
    'profile.photoUpdated': 'Profile photo updated.',
    'medical.openCard': 'Open donor card',
    'medical.totalDonations': 'Total donations',
    'donorCard.title': 'Donor card',
    'donorCard.digital': 'NBTS DIGITAL CARD',
    'donorCard.bloodVerified': 'Blood group verified',
    'donorCard.qrTitle': 'Express check-in',
    'donorCard.qrSubtitle': 'Show this code at any NBTS center.',
    'donorCard.homeCenter': 'Home center',
    'donorCard.qrExpires': 'QR expires',
    'donorCard.copied': 'Donor card details copied.',
    'complete.editProfile': 'Edit profile',
    'complete.completeProfile': 'Complete profile',
    'complete.editTitle': 'Edit your donor profile',
    'complete.finishTitle': 'Finish your donor profile',
    'complete.editSubtitle':
        'Update the donor details NBTS uses for eligibility, appointments, and your donor card.',
    'complete.finishSubtitle':
        'Google or Apple confirms your identity. NBTS still needs donor details before appointments and donor card access.',
    'complete.required': 'Required',
    'complete.optional': 'Optional',
    'complete.preferences': 'Preferences',
    'complete.address': 'Address',
    'complete.preferredCenter': 'Preferred blood center',
    'complete.emergencyName': 'Emergency contact name',
    'complete.emergencyPhone': 'Emergency contact phone',
    'complete.saveChanges': 'Save changes',
    'complete.saveContinue': 'Save and continue',
    'complete.useAnother': 'Use another account',
    'complete.loadingCenters': 'Loading centers',
    'complete.noCenters': 'No centers available',
    'complete.selectCenter': 'Select center',
    'book.title': 'Book donation',
    'book.rescheduleTitle': 'Reschedule donation',
    'book.center': 'Center',
    'book.date': 'Date',
    'book.time': 'Time',
    'book.donationCenter': 'Donation center',
    'book.chooseCenter': 'Choose center',
    'book.tip': 'Have a meal and water 2 hours before donating.',
    'book.selectTime': 'Select a time',
    'book.confirm': 'Confirm appointment',
    'book.save': 'Save appointment',
    'book.retry': 'Retry',
    'centers.title': 'Centers',
    'centers.subtitle':
        'Find NBTS locations, opening details, services, and booking availability.',
    'centers.search': 'Search by name or area',
    'centers.unavailable': 'Centers unavailable',
    'centers.loadFailed': 'Could not load donation centers.',
    'centers.none': 'No centers found',
    'centers.noneMessage': 'Try another area or pull to refresh NBTS centers.',
    'centers.addressPending': 'Address pending',
    'centers.hoursPending': 'Hours pending',
    'centers.phonePending': 'Phone pending',
    'centers.open': 'Open',
    'centers.closed': 'Closed',
    'centers.bookHere': 'Book here',
    'history.title': 'History',
    'history.subtitle':
        'Track your donation impact, verified visits, and next action.',
    'history.impact': 'Impact',
    'history.totalDonated': 'Total donated',
    'history.noRecords': 'No records yet',
    'history.noRecordsMessage':
        'Verified donation records will appear once NBTS syncs your data.',
    'history.scheduleNext': 'Schedule next donation',
    'history.records': 'Donation records',
    'history.recordsInfo':
        'This view shows all donation records currently synced from NBTS. Filters will become available when more record categories are provided by the backend.',
    'common.done': 'Done',
    'notifications.title': 'Notifications',
    'notifications.markRead': 'Mark read',
    'notifications.unavailable': 'Notifications unavailable',
    'notifications.empty': 'No notifications yet',
    'notifications.emptyMessage':
        'NBTS alerts, appointments, and campaign updates will appear here.',
    'appointments.title': 'Appointments',
    'appointments.unavailable': 'Appointments unavailable',
    'appointments.next': 'Next appointment',
    'appointments.all': 'All appointments',
    'appointments.noneBooked': 'No appointment booked',
    'appointments.noneBookedMessage':
        'Book a donation to see your upcoming visit details here.',
    'appointments.bookNew': 'Book new donation',
    'appointments.change': 'Change appointment',
    'appointments.noneYet': 'No appointments yet',
    'appointments.noneYetMessage':
        'Your upcoming and past bookings will appear here.',
    'appointments.cancelTitle': 'Cancel appointment?',
    'appointments.cancelMessage':
        'This appointment will be marked as cancelled.',
    'appointments.keep': 'Keep',
    'appointments.cancelAppointment': 'Cancel appointment',
    'appointments.cancelled': 'Appointment cancelled.',
    'appointments.status': 'Status',
    'appointments.reschedule': 'Reschedule',
    'appointments.cancel': 'Cancel',
    'appointments.datePending': 'Date pending',
    'appointments.centerPending': 'NBTS center',
    'dashboard.allClear': 'All clear',
    'dashboard.urgentRequest': 'Urgent request',
    'dashboard.noUrgent': 'No urgent blood requests right now',
    'dashboard.noUpcomingAppointment': 'No upcoming appointment',
    'dashboard.scheduled': 'Scheduled',
    'dashboard.manage': 'Manage',
    'dashboard.yourImpact': 'Your impact',
    'dashboard.impactCaption': 'Donations toward the next loyalty tier.',
    'dashboard.noForYou': 'No campaigns or articles available right now.',
    'dashboard.campaignUpdate': 'Campaign update',
    'dashboard.article': 'Article',
    'dashboard.noCampaignDetails': 'No campaign details provided yet.',
    'dashboard.noArticleDetails': 'No article details provided yet.',
    'book.chooseRequired': 'Choose a center, date, and time.',
    'book.timeUnavailable': 'This time is not available.',
    'book.activeExists':
        'You already have an active appointment. Reschedule or cancel it first.',
    'book.booked': 'Appointment booked.',
    'book.rescheduled': 'Appointment rescheduled.',
    'book.bookFailed': 'Could not book appointment.',
    'book.rescheduleFailed': 'Could not reschedule appointment.',
    'book.centersLoadFailed': 'Could not load donation centers.',
    'book.timesLoadFailed': 'Could not load available times.',
    'book.centersUnavailable': 'Centers unavailable',
    'book.timesUnavailable': 'Times unavailable',
    'book.chooseCenterDate': 'Choose a center and date to see available times.',
    'book.standardTimes':
        'Showing standard times until this center sends live availability.',
    'book.summary': 'Appointment summary',
    'book.chooseDate': 'Choose date',
    'book.chooseTime': 'Choose time',
    'profile.preferenceUpdated': 'Preference updated.',
    'profile.smsPhoneRequired':
        'Add a phone number before enabling SMS reminders.',
    'profile.smsReminderInfo':
        'SMS reminders are sent to your saved phone number.',
    'profile.languageUpdated': 'Language updated.',
    'profile.photoFailed': 'Could not update photo.',
    'profile.loadFailed': 'Could not load your profile.',
    'profile.unavailable': 'Profile unavailable',
    'profile.emergencyMessage':
        'Emergency contact editing is stored on the backend profile endpoint. Ask staff to verify this information before donation day.',
    'profile.faqMessage':
        'Bring a valid ID, eat before donating, drink water, and tell NBTS staff about medication or recent illness before donation.',
    'profile.contactMessage':
        'For urgent appointment or donor record support, contact your nearest NBTS center or use the center list in the app.',
    'profile.privacyMessage':
        'Your donor profile is used for eligibility, appointment reminders, donation history, and NBTS planning. You can sign out from this screen any time.',
    'history.loadFailed': 'Could not load donation history.',
    'history.unavailable': 'History unavailable',
    'history.centerFallback': 'NBTS center',
    'history.recorded': 'Recorded',
    'history.blood': 'Blood',
    'history.datePending': 'Date pending',
    'notifications.loadFailed': 'Could not load notifications.',
    'notifications.delete': 'Delete',
    'notifications.deleted': 'Notification deleted.',
    'notifications.deleteFailed': 'Could not delete notification.',
    'status.pendingConfirmation': 'Pending',
    'status.confirmed': 'Confirmed',
    'status.rescheduled': 'Rescheduled',
    'status.cancelled': 'Cancelled',
    'status.completed': 'Completed',
    'status.missed': 'Missed',
    'status.upcoming': 'Upcoming',
  };

  static const Map<String, String> _sw = {
    'app.name': 'NBTS',
    'welcome.title1': 'Changia damu.',
    'welcome.title2': 'Okoa maisha.',
    'welcome.subtitle':
        'Weka miadi ya kuchangia damu, fuatilia wasifu wako, na tumia kadi yako salama ya NBTS.',
    'welcome.feature.profile': 'Tengeneza na simamia wasifu wako wa mchangiaji',
    'welcome.feature.appointments': 'Weka na tazama miadi ya kuchangia',
    'welcome.feature.card': 'Beba kadi yako salama ya kidijitali',
    'auth.signIn': 'Ingia',
    'auth.createAccount': 'Fungua akaunti',
    'auth.loginSubtitle': 'Tumia barua pepe au simu uliyojisajili nayo.',
    'auth.emailPhone': 'Barua pepe au simu',
    'auth.emailPhoneHint': 'Barua pepe au namba ya simu',
    'auth.password': 'Nenosiri',
    'auth.newAccount': 'Mgeni NBTS?  Fungua akaunti',
    'auth.privacyAccept': 'Kwa kuendelea unakubali Sera ya Faragha.',
    'auth.registerTitle': 'Usajili wa mchangiaji',
    'auth.registerSubtitle':
        'Tupe taarifa zako ili kuanzisha wasifu wako wa NBTS.',
    'auth.account': 'Akaunti',
    'auth.fullName': 'Jina kamili',
    'auth.emailOptional': 'Barua pepe (si lazima)',
    'auth.phone': 'Simu',
    'auth.donorProfile': 'Wasifu wa mchangiaji',
    'auth.bloodGroup': 'Kundi la damu',
    'auth.gender': 'Jinsia',
    'auth.region': 'Mkoa',
    'auth.dateOfBirth': 'Tarehe ya kuzaliwa',
    'auth.selectDate': 'Chagua tarehe',
    'auth.terms': 'Ninakubali Masharti, Sera ya Faragha na taarifa ya afya.',
    'auth.haveAccount': 'Una akaunti tayari?  Ingia',
    'auth.required': 'Inahitajika',
    'auth.validEmail': 'Weka barua pepe sahihi',
    'auth.validPhone': 'Weka simu sahihi',
    'auth.passwordLength': 'Tumia angalau herufi 8',
    'nav.home': 'Nyumbani',
    'nav.book': 'Miadi',
    'nav.centers': 'Vituo',
    'nav.history': 'Historia',
    'nav.profile': 'Wasifu',
    'common.pending': 'Inasubiri',
    'common.pendingMedical': 'Inasubiri uthibitisho wa kitabibu',
    'common.seeAll': 'Tazama yote',
    'common.refresh': 'Onyesha upya',
    'dashboard.welcome': 'Karibu',
    'dashboard.welcomeDonor': 'Karibu mchangiaji',
    'dashboard.quickActions': 'Vitendo',
    'dashboard.forYou': 'Kwa ajili yako',
    'dashboard.eligibility': 'Ustahiki',
    'dashboard.eligible': 'Unastahiki',
    'dashboard.eligibleDonate': 'Unastahiki kuchangia',
    'dashboard.nextEligible': 'Ustahiki unaofuata',
    'dashboard.bookDonation': 'Weka miadi',
    'dashboard.donorCard': 'Kadi ya mchangiaji',
    'dashboard.donations': 'Michango',
    'dashboard.volume': 'Kiasi',
    'dashboard.findCenter': 'Kituo',
    'dashboard.card': 'Kadi',
    'profile.title': 'Wasifu',
    'profile.account': 'Akaunti',
    'profile.donorCard': 'Kadi ya mchangiaji',
    'profile.medicalSummary': 'Muhtasari wa afya',
    'profile.emergencyContact': 'Mawasiliano ya dharura',
    'profile.notifications': 'Arifa',
    'profile.pushNotifications': 'Arifa za programu',
    'profile.smsReminders': 'Vikumbusho vya SMS',
    'profile.appearance': 'Mwonekano',
    'profile.light': 'Mwanga',
    'profile.dark': 'Giza',
    'profile.system': 'Mfumo',
    'profile.language': 'Lugha',
    'profile.support': 'Msaada',
    'profile.faq': 'Maswali na mwongozo',
    'profile.contactSupport': 'Wasiliana na NBTS',
    'profile.privacy': 'Akaunti na faragha',
    'profile.signOut': 'Toka',
    'profile.nbtsId': 'NBTS ID',
    'profile.blood': 'Damu',
    'profile.donorPoints': 'Pointi',
    'profile.photoUpdated': 'Picha ya wasifu imesasishwa.',
    'medical.openCard': 'Fungua kadi ya mchangiaji',
    'medical.totalDonations': 'Jumla ya michango',
    'donorCard.title': 'Kadi ya mchangiaji',
    'donorCard.digital': 'KADI YA NBTS',
    'donorCard.bloodVerified': 'Kundi la damu limethibitishwa',
    'donorCard.qrTitle': 'Kuingia haraka',
    'donorCard.qrSubtitle':
        'Onyesha msimbo huu kwenye kituo chochote cha NBTS.',
    'donorCard.homeCenter': 'Kituo chako',
    'donorCard.qrExpires': 'QR inaisha',
    'donorCard.copied': 'Taarifa za kadi zimenakiliwa.',
    'complete.editProfile': 'Hariri wasifu',
    'complete.completeProfile': 'Kamilisha wasifu',
    'complete.editTitle': 'Hariri wasifu wako wa mchangiaji',
    'complete.finishTitle': 'Kamilisha wasifu wako wa mchangiaji',
    'complete.editSubtitle':
        'Sasisha taarifa NBTS inazotumia kwa ustahiki, miadi, na kadi yako.',
    'complete.finishSubtitle':
        'Google au Apple huthibitisha utambulisho wako. NBTS bado inahitaji taarifa za mchangiaji.',
    'complete.required': 'Inahitajika',
    'complete.optional': 'Si lazima',
    'complete.preferences': 'Mapendeleo',
    'complete.address': 'Anwani',
    'complete.preferredCenter': 'Kituo unachopendelea',
    'complete.emergencyName': 'Jina la mawasiliano ya dharura',
    'complete.emergencyPhone': 'Simu ya dharura',
    'complete.saveChanges': 'Hifadhi mabadiliko',
    'complete.saveContinue': 'Hifadhi na endelea',
    'complete.useAnother': 'Tumia akaunti nyingine',
    'complete.loadingCenters': 'Inapakia vituo',
    'complete.noCenters': 'Hakuna vituo',
    'complete.selectCenter': 'Chagua kituo',
    'book.title': 'Weka miadi',
    'book.rescheduleTitle': 'Badilisha miadi',
    'book.center': 'Kituo',
    'book.date': 'Tarehe',
    'book.time': 'Muda',
    'book.donationCenter': 'Kituo cha kuchangia',
    'book.chooseCenter': 'Chagua kituo',
    'book.tip': 'Kula chakula na kunywa maji saa 2 kabla ya kuchangia.',
    'book.selectTime': 'Chagua muda',
    'book.confirm': 'Thibitisha miadi',
    'book.save': 'Hifadhi miadi',
    'book.retry': 'Jaribu tena',
    'centers.title': 'Vituo',
    'centers.subtitle':
        'Tafuta vituo vya NBTS, saa za kazi, huduma, na nafasi za kuweka miadi.',
    'centers.search': 'Tafuta kwa jina au eneo',
    'centers.unavailable': 'Vituo havipatikani',
    'centers.loadFailed': 'Imeshindikana kupakia vituo.',
    'centers.none': 'Hakuna vituo vilivyopatikana',
    'centers.noneMessage':
        'Jaribu eneo jingine au vuta kusasisha vituo vya NBTS.',
    'centers.addressPending': 'Anwani inasubiri',
    'centers.hoursPending': 'Saa zinasubiri',
    'centers.phonePending': 'Simu inasubiri',
    'centers.open': 'Wazi',
    'centers.closed': 'Imefungwa',
    'centers.bookHere': 'Miadi hapa',
    'history.title': 'Historia',
    'history.subtitle':
        'Fuatilia mchango wako, ziara zilizothibitishwa, na hatua inayofuata.',
    'history.impact': 'Mchango wako',
    'history.totalDonated': 'Jumla iliyochangiwa',
    'history.noRecords': 'Hakuna rekodi bado',
    'history.noRecordsMessage':
        'Rekodi zilizothibitishwa zitaonekana NBTS ikisawazisha taarifa zako.',
    'history.scheduleNext': 'Panga mchango',
    'history.records': 'Rekodi za uchangiaji',
    'history.recordsInfo':
        'Hapa unaona rekodi zote zilizosawazishwa kutoka NBTS. Vichujio vitaongezwa backend ikitoa makundi zaidi.',
    'common.done': 'Sawa',
    'notifications.title': 'Arifa',
    'notifications.markRead': 'Weka zimesomwa',
    'notifications.unavailable': 'Arifa hazipatikani',
    'notifications.empty': 'Hakuna arifa bado',
    'notifications.emptyMessage':
        'Arifa za NBTS, miadi, na kampeni zitaonekana hapa.',
    'appointments.title': 'Miadi',
    'appointments.unavailable': 'Miadi haipatikani',
    'appointments.next': 'Miadi ijayo',
    'appointments.all': 'Miadi yote',
    'appointments.noneBooked': 'Hakuna miadi iliyowekwa',
    'appointments.noneBookedMessage':
        'Weka miadi ya kuchangia ili uone taarifa za ziara yako hapa.',
    'appointments.bookNew': 'Weka miadi mpya',
    'appointments.change': 'Badilisha miadi',
    'appointments.noneYet': 'Hakuna miadi bado',
    'appointments.noneYetMessage':
        'Miadi yako ya sasa na ya zamani itaonekana hapa.',
    'appointments.cancelTitle': 'Ghairi miadi?',
    'appointments.cancelMessage': 'Miadi hii itawekwa kama imeghairiwa.',
    'appointments.keep': 'Baki nayo',
    'appointments.cancelAppointment': 'Ghairi miadi',
    'appointments.cancelled': 'Miadi imeghairiwa.',
    'appointments.status': 'Hali',
    'appointments.reschedule': 'Badilisha',
    'appointments.cancel': 'Ghairi',
    'appointments.datePending': 'Tarehe inasubiri',
    'appointments.centerPending': 'Kituo cha NBTS',
    'dashboard.allClear': 'Hakuna dharura',
    'dashboard.urgentRequest': 'Ombi la dharura',
    'dashboard.noUrgent': 'Hakuna maombi ya dharura ya damu kwa sasa',
    'dashboard.noUpcomingAppointment': 'Hakuna miadi ijayo',
    'dashboard.scheduled': 'Imepangwa',
    'dashboard.manage': 'Simamia',
    'dashboard.yourImpact': 'Mchango wako',
    'dashboard.impactCaption': 'Michango kuelekea kiwango kinachofuata.',
    'dashboard.noForYou': 'Hakuna kampeni au makala kwa sasa.',
    'dashboard.campaignUpdate': 'Taarifa ya kampeni',
    'dashboard.article': 'Makala',
    'dashboard.noCampaignDetails': 'Hakuna maelezo ya kampeni bado.',
    'dashboard.noArticleDetails': 'Hakuna maelezo ya makala bado.',
    'book.chooseRequired': 'Chagua kituo, tarehe, na muda.',
    'book.timeUnavailable': 'Muda huu haupatikani.',
    'book.activeExists': 'Una miadi hai tayari. Badilisha au ghairi kwanza.',
    'book.booked': 'Miadi imewekwa.',
    'book.rescheduled': 'Miadi imebadilishwa.',
    'book.bookFailed': 'Imeshindikana kuweka miadi.',
    'book.rescheduleFailed': 'Imeshindikana kubadilisha miadi.',
    'book.centersLoadFailed': 'Imeshindikana kupakia vituo.',
    'book.timesLoadFailed': 'Imeshindikana kupakia muda.',
    'book.centersUnavailable': 'Vituo havipatikani',
    'book.timesUnavailable': 'Muda haupatikani',
    'book.chooseCenterDate': 'Chagua kituo na tarehe kuona muda uliopo.',
    'book.standardTimes':
        'Inaonyesha muda wa kawaida hadi kituo kitume nafasi halisi.',
    'book.summary': 'Muhtasari wa miadi',
    'book.chooseDate': 'Chagua tarehe',
    'book.chooseTime': 'Chagua muda',
    'profile.preferenceUpdated': 'Mapendeleo yamesasishwa.',
    'profile.smsPhoneRequired':
        'Ongeza namba ya simu kabla ya kuwasha vikumbusho vya SMS.',
    'profile.smsReminderInfo':
        'Vikumbusho vya SMS hutumwa kwenye namba yako ya simu iliyohifadhiwa.',
    'profile.languageUpdated': 'Lugha imesasishwa.',
    'profile.photoFailed': 'Imeshindikana kusasisha picha.',
    'profile.loadFailed': 'Imeshindikana kupakia wasifu wako.',
    'profile.unavailable': 'Wasifu haupatikani',
    'profile.emergencyMessage':
        'Mawasiliano ya dharura huhifadhiwa kwenye wasifu wa backend. Hakikisha NBTS wameyathibitisha kabla ya siku ya kuchangia.',
    'profile.faqMessage':
        'Beba kitambulisho, kula kabla ya kuchangia, kunywa maji, na waambie wahudumu wa NBTS kuhusu dawa au ugonjwa wa karibuni.',
    'profile.contactMessage':
        'Kwa msaada wa haraka kuhusu miadi au rekodi, wasiliana na kituo cha NBTS kilicho karibu au tumia orodha ya vituo.',
    'profile.privacyMessage':
        'Wasifu wako hutumika kwa ustahiki, vikumbusho vya miadi, historia ya uchangiaji, na mipango ya NBTS. Unaweza kutoka wakati wowote.',
    'history.loadFailed': 'Imeshindikana kupakia historia ya uchangiaji.',
    'history.unavailable': 'Historia haipatikani',
    'history.centerFallback': 'Kituo cha NBTS',
    'history.recorded': 'Imerekodiwa',
    'history.blood': 'Damu',
    'history.datePending': 'Tarehe inasubiri',
    'notifications.loadFailed': 'Imeshindikana kupakia arifa.',
    'notifications.delete': 'Futa',
    'notifications.deleted': 'Arifa imefutwa.',
    'notifications.deleteFailed': 'Imeshindikana kufuta arifa.',
    'status.pendingConfirmation': 'Inasubiri',
    'status.confirmed': 'Imethibitishwa',
    'status.rescheduled': 'Imebadilishwa',
    'status.cancelled': 'Imeghairiwa',
    'status.completed': 'Imekamilika',
    'status.missed': 'Imepitwa',
    'status.upcoming': 'Ijayo',
  };
}
